#!/usr/bin/env lua

local Map = require ('map.common')
local PJass = require ('map.tools.pjass')

local options = {
	['--version'] = Map.version
}

options ['--help'] = function ()
	io.stdout:write ([[
map build - Combine JASS scripts into a single file

Validates the syntax of the JASS scripts, then combines them into a single
file. The result is placed in the output directory.

Usage:
  build [options]
  build <configuration>

Options:
  --version    Displays the version number.
  --help       Displays this help message.
]])

	os.exit (0)
end

local map, message = Map.initialize (options)

if not map then
	io.stderr:write (message)
	os.exit (1)
end

if not Map.build_script (map.scripts, map.settings) then
	os.exit (1)
end

local patch = {}

for _, script in ipairs (map.patch) do
	table.insert (patch, script.path)
end

local status, output = PJass.check (map.settings.prefix,
	map.settings.pjass.options, patch, map.settings.output.script)

if status then
	io.stdout:write (output)
	os.exit (0)
else
	io.stderr:write (output)
	os.exit (1)
end
