#!/usr/bin/env lua

local Tasks = require ('map.tasks')

return Tasks.run {
	arguments = { ... },
	tasks = {
		'build'
	},

	help = [[
# map build

Packages the `war3map.lua`.  Performs all actions specified in the `check`
command.  Additionally, if the `map` settings table is provided, then a new
map will be built.  Changes to information exposed within the build
environment will be reflected within the built map.

## Usage
    build [options]
    build <configuration>

## Options
    --version    Displays the version number.
    --help       Displays this help message.]]
}
