#!/usr/bin/env lua

local Tasks = require ('map.tasks')

return Tasks.run {
	arguments = { ... },

	tasks = {
		'check'
	},

	help = [[
# map check

Check Lua modules using Luacheck.  A custom Luacheck standard representing
the Lua environment in Warcraft III is provided, and used by defult.

## Usage
    check [options]
    check <configuration>

## Options
    --version    Displays the version number.
    --help       Displays this help message.]]
}
