#!/usr/bin/env lua

local Map = require ('map.common')
local Globals = require ('map.globals')
local Grimex = require ('map.tools.grimex')
local Path = require ('map.path')

local options = {
	['--version'] = Map.version
}

options ['--help'] = function ()
	io.stdout:write ([[
map constants - Load constant data into the working map

Usage:
  constants [options]
  constants <configuration>

Options:
  --version    Displays the version number.
  --help       Displays this help message.
]])

	os.exit (0)
end

local map, message = Map.initialize (options)

if not map then
	io.stderr:write (message)
	os.exit (1)
end

if not Globals.write (map.settings.output.globals, map.globals) then
	os.exit (1)
end

local function merge_constants (name)
	local status, message = Map.check_files (map.settings.constants [name])

	if not status then
		io.stderr:write (message)
		return nil
	end

	local status, output = Grimex.constants (
		map.settings.prefix, map.settings.output.map,
		map.settings.output.globals, map.settings.constants [name])

	local output_log_path = Path.join (
		map.settings.output.directory, 'grimex-constants-' .. name .. '.txt')
	Grimex.log (output_log_path, output)

	if status then
		io.stdout:write (name .. ' settings: ok', '\n')
	else
		io.stderr:write (name .. ' settings: failure', '\n')
	end

	return status
end

local status = merge_constants ('gameplay')
status = merge_constants ('interface') and status

os.remove (map.settings.output.globals)

if status then
	os.exit (0)
else
	os.exit (1)
end
