#!/usr/bin/env lua

local Map = require ('map.common')
local Grimex = require ('map.tools.grimex')
local Path = require ('map.path')

local options = {
	['--version'] = Map.version
}

options ['--help'] = function ()
	io.stdout:write ([[
map imports - Load imports into the working map

Usage:
  imports [options]
  imports <configuration>

Options:
  --version    Displays the version number.
  --help       Displays this help message.
]])

	Map.exit (0)
end

local map, message = Map.initialize (options)

if not map then
	io.stderr:write (message)
	Map.exit (1)
end

local status, message = Map.check_files (map.settings.imports)

if not status then
	io.stderr:write (message)
	Map.exit (1, map)
end

local status, output = Grimex.imports (map.settings.prefix,
	map.settings.output.map, map.settings.imports)

output_log_path = Path.join (
	map.settings.output.directory, 'grimex-imports.txt')
Grimex.log (output_log_path, output)

if status then
	io.stdout:write ('imports: ok', '\n')
	Map.exit (0, map)
else
	io.stderr:write ('imports: failure', '\n')
	Map.exit (1, map)
end
