#!/usr/bin/env lua

local Map = require ('map.common')
local Globals = require ('map.globals')
local Grimex = require ('map.tools.grimex')
local Path = require ('map.path')

local options = {
	['--version'] = Map.version
}

options ['--help'] = function ()
	io.stdout:write ([[
map objects - Load object data into the working map

Usage:
  objects [options]
  objects <configuration>

Options:
  --version    Displays the version number.
  --help       Displays this help message.
]])

	Map.exit (0)
end

local map, message = Map.initialize (options, 'objects')

if not map then
	io.stderr:write (message)
	Map.exit (1)
end

if not Globals.write (map.settings.output.globals, map.globals) then
	Map.exit (1, map)
end

local status

status, message = Map.check_files (map.settings.objects)

if not status then
	io.stderr:write (message)
	Map.exit (1, map)
end

local output

status, output = Grimex.objects (
	map.settings.prefix, map.settings.output.map,
	map.settings.output.globals, map.settings.objects)

local output_log_path = Path.join (
	map.settings.output.directory, 'grimex-objects.txt')
Grimex.log (output_log_path, output)

os.remove (map.settings.output.globals)

if status then
	io.stdout:write ('objects: ok', '\n')
	Map.exit (0, map)
else
	io.stderr:write ('objects: failure', '\n')
	Map.exit (1, map)
end
