#!/usr/bin/env lua

local Map = require ('map.common')
local Optimizer = require ('map.tools.optimizer')

local options = {
	['--version'] = Map.version
}

options ['--help'] = function ()
	io.stdout:write ([[
map optimize - Create an optimized version of the working map

Usage:
  optimize [options]
  optimize <configuration>

Options:
  --version    Displays the version number.
  --help       Displays this help message.
]])

	Map.exit (0)
end

local map, message = Map.initialize (options)

if not map then
	io.stderr:write (message)
	Map.exit (1)
end

local optimized = map.settings.output.map:gsub ('%.w3x$', '-optimized.w3x')
local status = Optimizer.optimize (map.settings.prefix,
	map.settings.output.map, optimized, map.settings.optimizer.tweaks)

if status then
	io.stdout:write ('optimize: ok', '\n')
	Map.exit (0, map)
else
	io.stderr:write ('optimize: failure', '\n')
	Map.exit (1, map)
end
