#!/usr/bin/env lua

if not arg [1] or arg [1] == '--help' then
	io.stdout:write ([[
optimize - Create an optimized version of the working map

Usage:
  optimize [options]
  optimize <configuration>

Options:
  --help    Displays this help message.
]])

	os.exit (0)
end

local Settings = require ('map.settings')
local settings, message = Settings.read ()

if not settings then
	io.stdout:write (message, '\n')
	os.exit (1)
end

local Optimizer = require ('map.tools.optimizer')

local optimized = settings.output.map:gsub ('%.w3x$', '-optimized.w3x')
local status = Optimizer.optimize (settings.prefix,
	settings.output.map, optimized, settings.optimizer.tweaks)

if status then
	io.stdout:write ('Optimize: OK', '\n')
	os.exit (0)
else
	io.stderr:write ('Optimize: Failure', '\n')
	os.exit (1)
end
