#!/usr/bin/env lua

local Header = require ('map.header')
local Map = require ('map.common')
local Path = require ('map.path')
local W3I = require ('map.w3i')

local options = {
	['--version'] = Map.version
}

options ['--help'] = function ()
	io.stdout:write ([[
map prepare - Prepare the new working map

Updates the working map within the output directory, rebuilding trigger string
data if needed.

Usage:
  prepare [options]
  prepare [options] <configuration>

Options:
  --force      Force overwriting of map file. By default, will do
               nothing if the output file already exists.
  --version    Displays the version number.
  --help       Displays this help message.
]])

	os.exit (0)
end

local force

options ['--force'] = function ()
	force = true
end

local map, message = Map.initialize (options)

if not map then
	io.stderr:write (message)
	os.exit (1)
end

if force and Path.is_readable (map.settings.output.map) then
	os.remove (map.settings.output.map)
end

local status = Path.is_readable (map.settings.output.map)
	or Path.copy (map.settings.input.map, map.settings.output.map)

if not status then
	io.stderr:write ('error preparing map', '\n')
	os.exit (1)
end

local header = {
	name = map.settings.map.name
}

local status = Header.write (map.settings.output.map, header)

if not status then
	io.stderr:write ('error writing header', '\n')
	os.exit (1)
end

local information = {
	name = map.settings.map.name
}

local status = W3I.write (information, map.settings.output.map,
	map.settings.output.directory, map.settings.prefix)

if not status then
	io.stderr:write ('error updating w3i', '\n')
	os.exit (1)
end

io.stdout:write ('prepare: ok', '\n')
os.exit (0)
