#!/usr/bin/env lua

local Header = require ('map.header')
local Map = require ('map.common')
local Path = require ('map.path')
local W3I = require ('map.w3i')

local options = {
	['--version'] = Map.version
}

options ['--help'] = function ()
	io.stdout:write ([[
map prepare - Prepare the new working map

Updates the working map within the output directory, updating the map header
and war3map.w3i file is necessary.

Usage:
  prepare [options]
  prepare [options] <configuration>

Options:
  --force      Force overwriting of map file. By default, will do
               nothing if the output file already exists.
  --version    Displays the version number.
  --help       Displays this help message.
]])

	Map.exit (0)
end

local force

options ['--force'] = function ()
	force = true
end

local map, message = Map.initialize (options, 'prepare')

if not map then
	io.stderr:write (message)
	Map.exit (1)
end

if force and Path.is_readable (map.settings.output.map) then
	os.remove (map.settings.output.map)
end

local status = Path.is_readable (map.settings.output.map)
	or Path.copy (map.settings.input.map, map.settings.output.map)

if not status then
	io.stderr:write ('error preparing map', '\n')
	Map.exit (1, map)
end

local header = {
	name = map.settings.map.name
}

local status = Header.write (header, map.settings.output.map)

if not status then
	io.stderr:write ('error writing header', '\n')
	Map.exit (1, map)
end

local information = {
	name = map.settings.map.name,
	author = map.settings.map.author,
	description = map.settings.map.description,

	loading_screen = {
		text = map.settings.map.loading.text,
		title = map.settings.map.loading.title,
		subtitle = map.settings.map.loading.subtitle
	}
}

local status = W3I.write (information, map.settings.output.map,
	map.settings.output.directory, map.settings.prefix)

if not status then
	io.stderr:write ('error updating w3i', '\n')
	Map.exit (1, map)
end

io.stdout:write ('prepare: ok', '\n')
Map.exit (0, map)
